_target_: mi_estimator.MIEstimator
config:
  estimator: fdime_kl
  seq_length: ${data.config.seq_length}  # This will need to be set based on your variable
  alphabet_size: ${data.config.alphabet_size}  # Same as dim
  alpha: 1.0
  divergence: KL
  dropout: 0.2
  resnet_block_groups: ${resnet_block_groups}
  sigma_dim: null
  init_dim: ${init_dim}
  dim_mults:
    - 1
    - 1